In [47]:
import numpy as np


In [48]:
## Creatin a NumPy Array

list1 = [0,1,2,3,4]
arr = np.array(list1)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4]


In [49]:
## Adding the number 2 to every item in the list

arr = arr + 2
print(arr)

[2 3 4 5 6]


In [50]:
## Create a 2D array from a list of a list

list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2 = np.array(list2)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
## dtype argument

arr3 = np.array(list2, dtype='float')
print(arr3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [52]:
## astype argument

arr3_s = arr3.astype('int').astype('str')
print(arr3_s)

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]


In [53]:
## dtype = 'object'

arr_obj = np.array([1, 'a'], dtype='object')
print(arr_obj)

[1 'a']


In [54]:
## tolist() function

arr_list = arr_obj.tolist()
print(arr_list)

[1, 'a']


In [55]:
## Inspecting a NumPy array

print('Shape', arr3.shape)
print('Data Type', arr3.dtype)
print('Size', arr3.size)
print('Number of Dimensions', arr3.ndim)

Shape (3, 3)
Data Type float64
Size 9
Number of Dimensions 2


In [56]:
## Extracting specific items from an array

arr3 = np.array(list2, dtype='float')
print("whole:", arr3)
print("Part:", arr3[:2, :2])

whole: [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Part: [[0. 1.]
 [3. 4.]]


In [57]:
## Boolean Indexing

arr3 = np.array(list2, dtype='float')
boo = arr3 > 2
print(boo)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [58]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10])
print(new_series)

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64


In [59]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10])
print(new_series.values)
print('______________')
print(new_series[4])

[ 5  6  7  8  9 10]
______________
9


In [60]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])
print(new_series.values)
print('______________')
print(new_series['f'])

[ 5  6  7  8  9 10]
______________
10


In [61]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])
print(new_series)
print('______________')
new_series[['a','b','f']] = 0
print(new_series)

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64
______________
a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64


In [62]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])
new_series2 = new_series[new_series>0]
print(new_series2)
new_series2[new_series2>0]*2
print(new_series2)

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64
a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64


In [63]:
import pandas as pd
df = pd.DataFrame({
    'country': ['Kazakhstan','Russia','Belarus','Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2000000, 171000000, 2076000, 6035000]
})
print(df)


      country  population     square
0  Kazakhstan       17.04    2000000
1      Russia      143.50  171000000
2     Belarus        9.50    2076000
3     Ukraine       45.50    6035000


In [64]:
import pandas as pd
list2 = [[0,1,2],[3,4,5],[6,7,8]]
df = pd.DataFrame(list2)
print(df)
df.columns = ['V1', 'V2', 'V3']
print(df)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
   V1  V2  V3
0   0   1   2
1   3   4   5
2   6   7   8


In [65]:
import pandas as pd
df = pd.DataFrame({
    'country': ['Kazakhstan','Russia','Belarus','Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2000000, 171000000, 2076000, 6035000]
}, index = ['KZ', 'RU', 'BY', 'UA'])
print(df.columns)
print('____________')
print(df.index)

df.index.name = 'Country Code'
print(df)

Index(['country', 'population', 'square'], dtype='object')
____________
Index(['KZ', 'RU', 'BY', 'UA'], dtype='object')
                 country  population     square
Country Code                                   
KZ            Kazakhstan       17.04    2000000
RU                Russia      143.50  171000000
BY               Belarus        9.50    2076000
UA               Ukraine       45.50    6035000


In [66]:
print(df.loc['KZ'])

country       Kazakhstan
population         17.04
square           2000000
Name: KZ, dtype: object


In [67]:
print(df.iloc[0])

country       Kazakhstan
population         17.04
square           2000000
Name: KZ, dtype: object


In [68]:
print(df.loc[['KZ','RU'], 'population'])

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64


In [69]:
print(df.loc[['KZ','BY'], :])

                 country  population   square
Country Code                                 
KZ            Kazakhstan       17.04  2000000
BY               Belarus        9.50  2076000


In [70]:
print(df[df.population > 10][['country', 'square']])

                 country     square
Country Code                       
KZ            Kazakhstan    2000000
RU                Russia  171000000
UA               Ukraine    6035000


In [71]:
df = df.drop(['population'], axis='columns')
print(df)

                 country     square
Country Code                       
KZ            Kazakhstan    2000000
RU                Russia  171000000
BY               Belarus    2076000
UA               Ukraine    6035000
