Roj Gian Gorospe - 4CSC 
DATA ANALYIS AND VISUALIZATION

# Part 1: Introduction to NumPy

TASK 1. Creating Arrays

Create a 1D NumPy array containing the numbers from 1 to 15.

In [26]:
import numpy as np #Import numpy

numberList = []

for x in range(1, 16): # For loop for adding content of the list
    numberList.append(x)

print("List: " + str(numberList))  # Print List 

numpyArray = np.array(numberList) # Conversion of List to Numpy Array
 
print("Numpy Array: ", numpyArray)  # Print the NumPy array


List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Numpy Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


TASK 2. Reshaping Arrays

Reshape the 1D array from Task 1 into a 3x5 2D array.

In [27]:
reshapedArray = numpyArray.reshape(3, 5) # Reshapes the Numpy Array into a 3x5 2D Array

print("3x5 2D Array:\n", reshapedArray)

3x5 2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


TASK 3. Basic Arithmetic Operations

Create a new array by adding 2 to every element in the 2D array from Task 2.

In [28]:
addArray = reshapedArray + 2 # Adds 2 to every element in the 2D Array

print("3x5 2D Array + 2:\n", addArray)

3x5 2D Array + 2:
 [[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]


TASK 4. Array Indexing and Slicing

Extract the second row from the 2D array you created in Task 2.

In [29]:
print("2nd Row:", reshapedArray[1]) # Prints the extracted 2nd row

2nd Row: [ 6  7  8  9 10]


TASK 5. Element-wise Operations

Multiply each element in the 2D array by 3 and store the result in a new array.




In [30]:
multipliedArray = reshapedArray * 3 # Multiplies 3 to every element in the 2D Array and store to new array

print("Multiplied Array (by 3): ", multipliedArray)

Multiplied Array (by 3):  [[ 3  6  9 12 15]
 [18 21 24 27 30]
 [33 36 39 42 45]]


TASK 6. Basic Statistics

Calculate the mean and sum of all elements in the array from Task 5.

In [31]:
print("Mean of all elements: ",np.mean(multipliedArray)) # Uses the mean function of numpyArray
print("Sum of all elements: ",np.sum(multipliedArray)) # Uses the sum function of numpyArray

Mean of all elements:  24.0
Sum of all elements:  360


# Part 2: Introduction to Pandas

TASK 7. Creating DataFrames

Create a Pandas DataFrame using the following data:

 data = {
    'Name': ['Tom', 'Jane', 'Steve'],
    'Age': [28, 34, 29],
    'Salary': [50000, 60000, 55000]
}


In [32]:
import pandas as pd # Import pandas
data = pd.DataFrame({
    'Name': ['Tom', 'Jane', 'Steve'],
    'Age': [28, 34, 29],
    'Salary': [50000, 60000, 55000]
})

data

Name  Age  Salary
0    Tom   28   50000
1   Jane   34   60000
2  Steve   29   55000

TASK 8. Accessing DataFrame columns

Select the 'Name' column from the DataFrame and display it.

In [33]:
print("Names")
data['Name'] #Prints column 'Name'

Names


0      Tom
1     Jane
2    Steve
Name: Name, dtype: object

TASK 9. Adding a New Column

Add a new column to the DataFrame called 'Bonus', which is 10% of the 'Salary'.

In [34]:
data['Bonus'] = data['Salary'] * 0.10 # Adds a new column that has 10% of their Salary

data

Name  Age  Salary   Bonus
0    Tom   28   50000  5000.0
1   Jane   34   60000  6000.0
2  Steve   29   55000  5500.0

TASK 10. Basic DataFrame Statistics

Calculate the average salary of all individuals in the DataFrame.

In [35]:
print("Average Salary of all individuals: " ,data['Salary'].mean()) # Uses the mean function to calculate the average salary column for each individual


Average Salary of all individuals:  55000.0
